### ISSUE TITLE
LeetCode v2 Not Working

### ISSUE THREAD

**Issue by saivikas-dundumulla** [arunbhardwaj/LeetHub-2.0#57] opened 2023-11-30 14:51 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
LeetCode v2 Not Working

**To Reproduce**
Not Working by following the default steps

**Expected behavior**
Not able to push the code to the github repo

**Screenshots**

**Additional context**

**Comment by arunbhardwaj** [comment] 2024-04-18 19:57
Thank you for presenting the issue. The issue is fixed in the most recent update to the extension. Please update the extension!

**Closed by arunbhardwaj** 2024-04-18 19:57 UTC
Labels: bug
