### ISSUE TITLE
It doesn't deploy my code intially when i was started with this extension it works but now!

### ISSUE THREAD

**Issue by suriya216** [arunbhardwaj/LeetHub-2.0#67] opened 2024-03-04 09:48 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arunbhardwaj** [comment] 2024-04-18 19:59
Thank you for presenting the issue. The issue is fixed in the most recent update to the extension. Please update the extension!

**Closed by arunbhardwaj** 2024-04-18 19:59 UTC
