### ISSUE TITLE
LH V2 is not working anymore

### ISSUE THREAD

**Issue by bendumanoharnaidu2001** [arunbhardwaj/LeetHub-2.0#56] opened 2023-11-23 01:41 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**

**To Reproduce**

**Expected behavior**

It's been two weeks it's not counting the solved problems or uploading on leetcode

**Screenshots**
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/45328696/a1c09849-f69f-4f2d-8d1d-24ae107f399c)

**Additional context**

**Comment by aystream** [comment] 2023-11-23 08:18
Duplicate issue, please look https://github.com/arunbhardwaj/LeetHub-2.0/issues/51 and close this one

**Comment by arunbhardwaj** [comment] 2024-04-18 19:58
Thank you for presenting the issue. The issue is fixed in the most recent update to the extension. Please update the extension!

**Closed by arunbhardwaj** 2024-04-18 19:58 UTC
Labels: bug
