### ISSUE TITLE
Its Not Working 

### ISSUE THREAD

**Issue by Abuthair11** [arunbhardwaj/LeetHub-2.0#62] opened 2024-01-08 17:21 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by arunbhardwaj** [comment] 2024-04-18 19:57
Thank you for presenting the issue. The issue is fixed in the most recent update to the extension. Please update the extension!

**Closed by arunbhardwaj** 2024-04-18 19:57 UTC
Labels: bug
