### ISSUE TITLE
Not able to sync

### ISSUE THREAD

**Issue by Abhinavgit123** [arunbhardwaj/LeetHub-2.0#65] opened 2024-02-26 04:11 UTC
Description
Unable to sync to github since the new layout of leetcode.
Please try to fix it soon!

**Comment by arunbhardwaj** [comment] 2024-04-18 19:56
Thank you for presenting the issue. The issue is fixed in the most recent update to the extension. Please update the extension!

**Closed by arunbhardwaj** 2024-04-18 19:56 UTC
Labels: bug
