### ISSUE TITLE
Not Pushing Codes Over GitHub

### ISSUE THREAD

**Issue by wittedtech** [arunbhardwaj/LeetHub-2.0#76] opened 2024-05-23 15:48 UTC
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
Extension is working fine. Did al the steps to set it up But the codes i do over on leetcode diesn't gets pushed in the github repository.

**To Reproduce**
1. Go to 'Leetcode.com'
2. Solve any Problem
3. Click on Submit
4. After Submission the process gets recorded but the code doesn't gets pushed on GitHub

**Expected behavior**
Should have pushed the code in the github.com inside a linked repository.

**Screenshots**

![Screenshot 2024-05-23 at 9 17 42 PM](https://github.com/arunbhardwaj/LeetHub-2.0/assets/81770777/57a00fb4-31d1-473f-b929-f89ee84b4029)

![Screenshot 2024-05-23 at 9 17 25 PM](https://github.com/arunbhardwaj/LeetHub-2.0/assets/81770777/a8744fd4-fce0-4a60-a877-cecc62473cef)

**Comment by AYSTRONGIRP** [comment] 2024-05-24 08:53
i am also facing the same bug .

**Comment by arunbhardwaj** [comment] 2024-05-24 13:24
Can you confirm that you are using [LeetHub v2](https://chromewebstore.google.com/detail/leethub-v2/mhanfgfagplhgemhjfeolkkdidbakocm?hl=en&pli=1)? The UI depicted in the second photo seems to be a different extension.

**Comment by AYSTRONGIRP** [comment] 2024-05-24 19:27
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/83717769/4e4d5e13-38c8-47e1-9dd5-c4278c5f0d29)
Yeah sure .

**Comment by arunbhardwaj** [comment] 2024-05-27 06:03
I've reproduced the issue. It occurs in two scenarios: you are using the Toolbar Layout for Submit button, or you submitted a successful submission after an incorrect one. I should have a fix soon. 

For now, you can successfully push your submissions if you use the other Submit button layout by going to the gear icon > Dynamic Layout > Show Run / Submit / Debug buttons in > Code Editor.

**Comment by arunbhardwaj** [comment] 2024-05-30 16:32
Deployed in v2.0.2. Please update your extension if it's not done automatically!

**Comment by dsankov** [comment] 2024-05-31 17:39
I've just upgraded to v2.0.3 but the problem is still there.
There is everything OK while using "old version".
But when switched to "new version", submitting the code doesn't push it to github. Regardless of submit button layout

**Comment by arunbhardwaj** [comment] 2024-05-31 17:54
@dsankov can you share steps to reproduce along with some screenshots of what you're seeing on LeetCode and within your developer console?

**Comment by arunbhardwaj** [comment] 2024-06-01 17:19
@dsankov I'm very glad the extension is working for you now! @AYSTRONGIRP @wittedtech I'll be closing this ticket for now, but please let me know if the problem persists for you still and I'll come back to take a look.

**Closed by arunbhardwaj** 2024-06-01 17:19 UTC
Labels: bug
